// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7QIzvtwDoxAcvULUGN9WlxD_6r10VZs',
    appId: '1:669795811976:web:bf0512c54298c99f15553d',
    messagingSenderId: '669795811976',
    projectId: 'ropulva-2b81a',
    authDomain: 'ropulva-2b81a.firebaseapp.com',
    storageBucket: 'ropulva-2b81a.appspot.com',
    measurementId: 'G-7KKY82QMSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnVX6v5MM0FTziDAgDXIukkx9vnLkQTg',
    appId: '1:669795811976:android:4abd80e40a41e09515553d',
    messagingSenderId: '669795811976',
    projectId: 'ropulva-2b81a',
    storageBucket: 'ropulva-2b81a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-9qXp6IR1amMBVa9RsGogZtsRBUORM2k',
    appId: '1:669795811976:ios:2146d92afc472ba215553d',
    messagingSenderId: '669795811976',
    projectId: 'ropulva-2b81a',
    storageBucket: 'ropulva-2b81a.appspot.com',
    iosBundleId: 'com.example.ropulvaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-9qXp6IR1amMBVa9RsGogZtsRBUORM2k',
    appId: '1:669795811976:ios:2146d92afc472ba215553d',
    messagingSenderId: '669795811976',
    projectId: 'ropulva-2b81a',
    storageBucket: 'ropulva-2b81a.appspot.com',
    iosBundleId: 'com.example.ropulvaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG7QIzvtwDoxAcvULUGN9WlxD_6r10VZs',
    appId: '1:669795811976:web:9b9f4257fe0b3bd115553d',
    messagingSenderId: '669795811976',
    projectId: 'ropulva-2b81a',
    authDomain: 'ropulva-2b81a.firebaseapp.com',
    storageBucket: 'ropulva-2b81a.appspot.com',
    measurementId: 'G-LNRX2ZXGPZ',
  );
}
